a.out:SLL.o Add_end.o display.o Add_beg.o search.o delete.o delete_last.o save.o synchfile.o reverse.o Add_nodeAt_N.o Fast_Slow.o
	cc SLL.o Add_end.o display.o Add_beg.o search.o delete.o delete_last.o save.o synchfile.o reverse.o Add_nodeAt_N.o Fast_Slow.o

SLL.o:SLL.c
	cc -c SLL.c

Add_end.o:Add_end.c
	cc -c Add_end.c

display.o:display.c
	cc -c display.c

Add_beg.o:Add_beg.c
	cc -c Add_beg.c

search.o:search.c
	cc -c search.c

delete.o:delete.c
	cc -c delete.c
delete_last.o:delete_last.c
	cc -c delete_last.c

save.o:save.c
	cc -c save.c

synchfile.o:synchfile.c
	cc -c synchfile.c

reverse.o:reverse.c
	cc -c reverse.c

Add_nodeAt_N.o:Add_nodeAt_N.c
	cc -c Add_nodeAt_N.c

Fast_Slow.o:Fast_Slow.c
	cc -c Fast_Slow.c
