a.out:main.o strlen.o strcmp.o strcpy.o strcat.o atoi.o atof.o strstr.o memmove.o
	cc main.c strlen.o strcmp.o strcpy.o strcat.o atoi.o atof.o strstr.o memmove.o

main.o:main.c
	cc -c main.c

strlen.o:strlen.c
	cc -c strlen.c

strcmp.o:strcmp.c
	cc -c strcmp.c

strcpy.o:strcpy.c
	cc -c strcpy.c

strcat.o:strcat.o
	cc -c strcat.c

atoi.o:atoi.c
	cc -c atoi.c

atof.o:atof.c
	cc -c atof.c

strstr.o:strstr.c
	cc -c strstr.c

memmove.o:memmove.c
	cc -c memmove.c
