a.out: insert.o binary_Tree.o in_order.o  pre_order.o post_order.o findmin.o search.o
	cc insert.o binary_Tree.o in_order.o  pre_order.o post_order.o findmin.o search.o

binary_Tree.o: binary_Tree.c
	cc -c binary_Tree.c

in_order.o: in_order.c
	cc -c in_order.c

pre_order.o: pre_order.c
	cc -c pre_order.c

post_order.o: post_order.c
	cc -c post_order.c

insert.o: insert.c
	cc -c insert.c
       	
findmin.o:findmin.c
	cc -c findmin.c

search.o:search.c
	cc -c search.c
