a.out: sort.o bubble.o input.o display.o selection.c insertion.o mergesort.o 
	cc sort.c bubble.c input.c display.c selection.c insertion.c mergesort.c 

sort.o: sort.c
	cc -c sort.c

bubble.o: bubble.c
	cc -c bubble.c

input.o:input.c
	cc -c input.c

display.o:display.c
	cc -c display.c

selection.o:selection.c
	cc -c selection.c

insertion.o:insertion.c
	cc -c insertion.c

mergesort.o:mergesort.c
	cc -c mergesort.c
